### ISSUE TITLE
Checklist - Project Requirements

### ISSUE THREAD

**Issue by omarwright07** [omarwright07/music-guru#4]
## Summary
You and your group will use everything you’ve learned over the past six weeks to create a real-world front-end application that you’ll be able to showcase to potential employers. The user story and acceptance criteria will depend on the project that you create, but there are some requirements that your project must fulfill.

The requirements for this project ask you to use the skills and technologies you’ve learned over the past six weeks (deployment, interactivity, client-side storage, responsive design, polished UI).

They also ask you to use some of the less obvious skills you’ve practiced in the lessons and in your class. You’ve learned that there are many frameworks used in web development. You’ve already experienced what it’s like digging through Bootstrap’s documentation—now use the skills you’ve developed to dive into the documentation for an alternative framework.

The lessons and Challenge assignments have reinforced the importance of quality coding standards and best practices for repositories and READMEs. Use these skills to create a professional and impressive application that you could present with pride to any potential employer.

Finally, these requirements ask you to place your work in the context of your future career by adding your project to your portfolio. Each module’s Career Connection has prepared you for life after this boot camp. Getting your first developer role requires you to have applications in your portfolio so that employers can see your work.

## Your project should fulfill the following requirements:
- [ ] Use a CSS framework other than Bootstrap.
- [ ] Be deployed to GitHub Pages.
- [ ] Be interactive (i.e., accept and respond to user input).
- [ ] Use at least two server-side APIs.
- [ ] Does not use alerts, confirms, or prompts (use modals).
- [ ] Use client-side storage to store persistent data.
- [ ] Be responsive.
- [ ] Have a polished UI.

## Have a quality README with 
- [ ] Unique name
- [ ] Description
- [ ] Technologies Used
- [ ] Screenshot
- [ ] Link to deployed application

## Special Notes:
1. Have a clean repository that meets quality coding standards (file structure, naming conventions, follows best practices for class/id naming conventions, indentation, quality comments, etc.).
2. Finally, you must add your project to the portfolio that you created in Module 2.

**Comment by brynnke** [comment]
https://docs.ksoft.si/api/lyrics-api 
could use this ?
